### ISSUE TITLE
Snitcher report 15523400  - Error

### ISSUE THREAD

**Issue by cusspvz** [cusspvz/snitcher-reporter-api-test#1]
Error: YOLO

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align=right>
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align=right>
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)
```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x:

An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

#### Error

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
:x: Error: YOLO
An error has occured and i did my f*cking job!
Now its your turn, you little code monkey :monkey_face:

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
### :x: Error

##### could not found 'undefined' of  'undefined'

<sup>
:monkey_face: An error has occured and i did my f*cking job, now its your turn, you little code monkey.
</sup>

###### Stack

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
### :x: Error##### YOLO

<sup>
:monkey_face: An error has occured and i did my f*cking job, now its your turn, you little code monkey.
</sup>

###### Stack:

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>

**Comment by cusspvz** [comment]
### :x: Error

##### YOLO

<sup>
:monkey_face: An error has occured and i did my f*cking job, now its your turn, you little code monkey.
</sup>

###### Stack:

```
Error: YOLO
  at Context.<anonymous> (/Users/josemoreira/GitHub/findhit/snitcher/test/reporter/github.test.js:74:51)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:266:21)
  at Test.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at Runner.runTest (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:390:10)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:473:12
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:315:14)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:325:7
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:260:23)
  at /Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:287:7
  at done (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:222:5)
  at callFn (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:277:7)
  at Hook.Runnable.run (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runnable.js:259:7)
  at next (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:271:10)
  at Immediate._onImmediate (/Users/josemoreira/GitHub/findhit/snitcher/node_modules/mocha/lib/runner.js:292:5)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

```

<div align="right">
    <sub>
        <sup>
            reported by <a href="https://github.com/findhit/snitcher">Snitcher</a>!
        </sup>
    </sub>
</div>
